### PR TITLE
Function help in PixelData.get data is incorrect

### LINKED ISSUE #418: Function help in PixelData.get_data is incorrect
https://github.com/pace-neutrons/Horace/pull/415 updated `PixelData.get_data` to use absolute indexing. The function help was not changed to reflect this and still states the function indexes into the current page.

**Outputs:**
- The help in `PixelData.get_data` should describe the behaviour of the function accurately

### PR DESCRIPTION
**Pull request by hsautessella**
Update the help in `PixelData.get_data` to reflect the new behaviour introduced in https://github.com/pace-neutrons/Horace/pull/415.

Fixes #418.

### CODE REVIEW

File: horace_core/sqw/PixelData/@PixelData/get_data.m [hunk 1]
```diff
@@ -1,18 +1,18 @@
...
 % columns of data will be ordered corresponding to the order the fields
 % appear in the inputted cell array.
 %
 %   >> sig_and_err = pix.get_data({'signal', 'variance'})
-%        retrives the signal and variance over the whole range of pixels
+%        retrieves the signal and variance over the whole range of pixels
 %
 %   >> run_det_id_range = pix.get_data({'run_idx', 'detector_idx'}, 4:10);
-%        retrives the run and detector IDs for pixels 4 to 10
+%        retrieves the run and detector IDs for pixels 4 to 10
```
Comment (nickbattam-tessella) [inline horace_core/sqw/PixelData/@PixelData/get_data.m:15]: I suggest using pixel numbers in this example that are obviously "big" and mention the word "absolute pixel index" e.g. `15640:19244`

File: horace_core/sqw/PixelData/@PixelData/get_pixels.m [hunk 2]
```diff
@@ -1,8 +1,8 @@
 function pix_out = get_pixels(obj, abs_pix_indices)
-% GET_PIXELS Retrieve the pixels at the given indices in the current page, return
-% a new PixelData object
+% GET_PIXELS Retrieve the pixels at the given indices relative to the full
```
Comment (nickbattam-tessella) [inline horace_core/sqw/PixelData/@PixelData/get_pixels.m:2]: "relative" is a dangerous word to use here; they're absolute indexes...

**Review by nickbattam-tessella — APPROVED** [review]
