### PR TITLE
legacy alignment off

### LINKED ISSUE #1141: Legacy alignment should be removed
Legacy alignment inconsistent with generic projection. It is also does not processes projection correctly, so that pixel ranges in case of large rotation become incorrect. As such legacy alignment should be removed and data, processed with legacy alignment should be converted into new alignment at load.

### PR DESCRIPTION
**Pull request by abuts**
Set of routines which would allow to modify legacy alignment and convert it into modern alignment. 
Was trying to make this change automatic, but as the transformation needs the knowlege of original lattice, user have to provide this information. Manual intervention is needed.

Fixes #1141

### CODE REVIEW

File: horace_core/algorithms/upgrade_legacy_alignment.m [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+%
+%   >> upgrade_legacy_alignment(filenames, alatt0,angdeg0)
+% modify legacy alignment previously
+%                                                 % of the crystal according to the
+%                                                 % crystal alignment information provided
+%
+%
+% Input:
+% -----
+%   w          cellarray of Input sqw objects or file names for sqw files,
```
Comment (cmarooney-stfc) [inline horace_core/algorithms/upgrade_legacy_alignment.m:13]: it's called in_data in the function line

File: horace_core/algorithms/upgrade_legacy_alignment.m [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+end
+hc = hor_config;
+ll = hc.log_level;
+
+% Perform operations
+out = cell(1,numel(in_data));
+for i=1:numel(in_data)
+    if isa(in_data{i},'SQWDnDBase')
+        out{i} = in_data{i}.upgrade_legacy_alignment(alatt0,angdeg0);
+    else
```
Comment (cmarooney-stfc) [inline horace_core/algorithms/upgrade_legacy_alignment.m:45]: should test this is a filename

File: horace_core/sqw/@DnDBase/remove_legacy_alignment.m [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+ub_inv_legacy = obj.proj.ub_inv_legacy;
+if isempty(ub_inv_legacy)
+    error('HORACE:DnDBase:invalid_argument', ...
+        'Object does not contain legacy alignment matrix. Nothing to do');
+end
+
+if all(abs(subdiag_elements(ub_inv_legacy))<4*eps('single')) && ~lattice_modified
+    % nothing to do, object has not been aligned
+    error('HORACE:DnDBase:invalid_argument', ...
+        'Object has not been legacy-aligned. Nothing to do');
```
Comment (cmarooney-stfc) [inline horace_core/sqw/@DnDBase/remove_legacy_alignment.m:59]: ditto

File: horace_core/sqw/@DnDBase/upgrade_legacy_alignment.m [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+%           not been realigned using legacy algorithm.
+% Optional
+% alatt   -- lattice parameters with new values for lattice. (presumably
+%            before alignment)
+% angdeg  -- lattice angles with values necessary to set.
+%            Of one is present, another one have to be present.
+%            If these values are missing, assumes that the lattice have not
+%            been changed.
+% Outputs:
+% wout    -- dealigned dnd object
```
Comment (cmarooney-stfc) [inline horace_core/sqw/@DnDBase/upgrade_legacy_alignment.m:17]: do you mean dealigned or realigned?

**Review by cmarooney-stfc — CHANGES_REQUESTED** [review]

File: horace_core/algorithms/upgrade_legacy_alignment.m (hunk 2 above)
Comment (abuts) [reply horace_core/algorithms/upgrade_legacy_alignment.m:45]: faccessor is extensively testing its input and will throw if found something inappropriate.

File: horace_core/algorithms/upgrade_legacy_alignment.m [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+%
+
+% This routine used to change the crystal in sqw files, when it overwrites the input file.
+
+% Parse input
+% -----------
+if ischar(in_data) % process single file
+    in_data = {in_data};
+end
+if ~isnumeric(alatt0) || ~isnumeric(angdeg0) || numel(alatt0) ~= 3 || numel(angdeg0) ~= 3 || nargin < 3
```
Comment (oerc0122) [inline horace_core/algorithms/upgrade_legacy_alignment.m:33]: Do we want to make `is_3vector` and `is_3x3matrix` from `Symop` a public utility function?

File: horace_core/sqw/@DnDBase/remove_legacy_alignment.m [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+%            If these values are missing, assumes that the lattice have not
+%            been changed.
+%
+%
+% Throws invalid_argument if identified that crystal has not been realigned
+
+if nargin > 1
+    if nargin ~= 3
+        error('HORACE:DnDBase:invalid_argument', ...
+            'If lattice parameters are provided as input (%s) lattice angles have to be provieded too. Got %d input parameters', ...
```
Comment (oerc0122) [inline horace_core/sqw/@DnDBase/remove_legacy_alignment.m:32]:
```suggestion
            'If lattice parameters are provided as input (%s) lattice angles have to be provided. Only got %d input parameters', ...
```

File: horace_core/sqw/@DnDBase/remove_legacy_alignment.m [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+            disp2str(varargin{1}),nargin);
+    end
+    % use tmp proj class to check the lattice parameters validity
+    tmp_proj = ortho_proj('alatt',varargin{1},'angdeg',varargin{2});
+    alatt = tmp_proj.alatt;
+    angdeg = tmp_proj.angdeg;
+    if any(abs(alatt-obj.alatt)>4*eps('single')) || ...
+            any(abs(angdeg-obj.angdeg)>4*eps('single'))
```
Comment (oerc0122) [inline horace_core/sqw/@DnDBase/remove_legacy_alignment.m:40]:
```suggestion
    if ~equal_to_tol(alatt, obj.alatt, 'tol', 4*eps('single')) || ...
        ~equal_to_tol(angdeg, obj.angdeg, 'tol', 4*eps('single'))
```

File: horace_core/sqw/@DnDBase/remove_legacy_alignment.m [hunk 8]
```diff
@@ -0,0 +1,71 @@
...
+    angdeg           = obj.angdeg;
+    lattice_modified = false;
+end
+ub_inv_legacy = obj.proj.ub_inv_legacy;
+if isempty(ub_inv_legacy)
+    error('HORACE:DnDBase:invalid_argument', ...
+        'Object does not contain legacy alignment matrix. Nothing to do');
+end
+
+if all(abs(subdiag_elements(ub_inv_legacy))<4*eps('single')) && ~lattice_modified
```
Comment (oerc0122) [inline horace_core/sqw/@DnDBase/remove_legacy_alignment.m:56]:
```suggestion
if equal_to_tol(subdiag_elements(ub_inv_legacy), zeros(6, 1), 'tol', 4*eps('single')) && ~lattice_modified
```

File: horace_core/sqw/@DnDBase/upgrade_legacy_alignment.m [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+%            Of one is present, another one have to be present.
+%
+% Does nothing if identified that crystal has not been legacy realigned
+
+alatt_al     = obj.alatt;
+angdeg_al    = obj.angdeg;
+no_alignment = false;
+try
+    [obj,al_info,alatt0,angdeg0] = remove_legacy_alignment(obj,varargin{:});
+catch ME
```
Comment (oerc0122) [inline horace_core/sqw/@DnDBase/upgrade_legacy_alignment.m:34]: As @cmarooney-stfc noted, error handling shouldn't be used to control flow like this.

File: horace_core/sqw/@Experiment/remove_legacy_alignment.m [hunk 10]
```diff
@@ -0,0 +1,50 @@
...
+% al_info -- instance of crystal_alignment_info class, containing alignment
+%            parameters, used to do legacy alignment.
+
+%
+sam = obj.samples;
+exper = obj.expdata;
+alatt = al_info.alatt;
+angdeg = al_info.angdeg;
+al_info.hkl_mode = true;
+% define rotation in opposite direction, to compencate for previous
```
Comment (oerc0122) [inline horace_core/sqw/@Experiment/remove_legacy_alignment.m:30]:
```suggestion
% define rotation in opposite direction, to compensate for previous
```

File: horace_core/sqw/@Experiment/remove_legacy_alignment.m [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+%
+% Inputs:
+% obj    -- legacy realigned dnd object. Algorithm throws if the object has
+%           not been realigned using legacy algorithm.
+% al_info 
+%       -- instance of crystal_alignment_info class, containing information
+%          about the alignment
+% Optional
+% alatt   -- lattice parameters with new values for lattice. (presumably
+%            before alignment)
```
Comment (oerc0122) [inline horace_core/sqw/@Experiment/remove_legacy_alignment.m:14]: Surely we should be sure what the user should put in.

File: horace_core/sqw/@Experiment/upgrade_legacy_alignment.m [hunk 12]
```diff
@@ -0,0 +1,36 @@
...
+%
+% Inputs:
+% obj    -- legacy realigned dnd object. Algorithm throws if the object has
+%           not been realigned using legacy algorithm.
+% al_info
+%       -- instance of crystal_alignment_info class, containing information
+%          about the alignment
+% Optional
+% alatt0  -- lattice parameters with new values for lattice. (presumably
+%            before alignment)
```
Comment (oerc0122) [inline horace_core/sqw/@Experiment/upgrade_legacy_alignment.m:15]: Again

File: horace_core/sqw/@Experiment/upgrade_legacy_alignment.m [hunk 13]
```diff
@@ -0,0 +1,36 @@
...
+% al_info -- instance of crystal_alignment_info class, containing alignment
+%            parameters, used to do legacy alignment.
+
+%
+alatt_new  = al_info.alatt;
+angdeg_new = al_info.angdeg;
+if nargin>2
+    al_info.alatt  = alatt0;
+    al_info.angdeg = angdeg0;
+else
```
Comment (oerc0122) [inline horace_core/sqw/@Experiment/upgrade_legacy_alignment.m:31]: Don't need empty else
```suggestion
```

**Review by oerc0122 — CHANGES_REQUESTED** [review]

File: horace_core/sqw/@DnDBase/upgrade_legacy_alignment.m (hunk 4 above)
Comment (abuts) [reply horace_core/sqw/@DnDBase/upgrade_legacy_alignment.m:17]: modified

File: _test/test_change_crystal/test_change_crystal_bragg_coarse.m [hunk 14]
```diff
@@ -122,16 +122,125 @@ function test_u_alighnment_tf_way(obj)
...
+            wout_modern = change_crystal (test_obj,corrections);
+
+            assertEqualToTol(al_info,corrections,'tol',1.e-9)
+            assertEqual(wout_modern,obj_realigned);
+        end
+
+        function test_remove_legacy_keep_lattice_change_fails(obj)
+            % testing the possibility to dealign the crystal, aligned by
+            % legacy algorithm if original lattice is unknown
+            test_obj = read_sqw(obj.misaligned_sqw_file);
```
[the remark this answers is not in the document]
Comment (abuts) [reply _test/test_change_crystal/test_change_crystal_bragg_coarse.m:192]: I believe, `read_sqw` should have its place. First, its used in all old script, second -- it should try to load all object in memory (not sure it is indeed forced). Then the familiar behaviour should be maintained to old user. `sqw` would build file/memory based object on the basis of the configuration, and each behaviour should be switchable using appropriate keywords.

File: horace_core/algorithms/upgrade_legacy_alignment.m [hunk 15]
```diff
@@ -0,0 +1,76 @@
...
+% -------
+%   wout      cellarray of iutput sqw objects and filename containing sqw
+%             objects modified
+%
+
+% This routine used to change the crystal in sqw files, when it overwrites the input file.
+
+% Parse input
+% -----------
+if ischar(in_data) % process single file
```
[the remark this answers is not in the document]
Comment (abuts) [reply horace_core/algorithms/upgrade_legacy_alignment.m:30]: single sqw object will use the same class method through

File: horace_core/algorithms/upgrade_legacy_alignment.m (hunk 5 above)
Comment (abuts) [reply horace_core/algorithms/upgrade_legacy_alignment.m:33]: I am not sure but probably it would rather complicate the code understanding then simplify it. Yes, experienced users would benifit from it, but you will forget it after some time. 
The code here is not very complicated and easy to read (and I have some similar checks in projection too) so I would leave it as it is. But not sure.

Comment (oerc0122) [reply horace_core/algorithms/upgrade_legacy_alignment.m:33]: That's kind of the point. We have a lot of points where we check for 3-vectors and 3x3 matrices. 
```
if ~is_3vector(alatt0) || ~is_3vector(angdeg) || nargin < 3
```
Isn't exactly compicated

File: horace_core/sqw/@DnDBase/remove_legacy_alignment.m (hunk 7 above)
Comment (abuts) [reply horace_core/sqw/@DnDBase/remove_legacy_alignment.m:40]: `equalt_to_tol` is complex function which analyzes various input parameters types and forms proper message which allows to identify the difference. Its primary usage is testing. Despite its not a performance critical part of code, I would rather not use it for simple check within workflow.

File: horace_core/sqw/@DnDBase/remove_legacy_alignment.m (hunk 8 above)
Comment (abuts) [reply horace_core/sqw/@DnDBase/remove_legacy_alignment.m:56]: the same as above

File: horace_core/sqw/@DnDBase/upgrade_legacy_alignment.m (hunk 9 above)
Comment (abuts) [reply horace_core/sqw/@DnDBase/upgrade_legacy_alignment.m:34]: I think reply to him holds. error is appropriate for removal.
