### PR TITLE
Fix issue with cut_sym not transforming pixels

### LINKED ISSUE #1620: Pixels not fully transformed in cut_sym
Currently `cut` with symmetry does not transform the pixels when they are rebinned in a symmetrised cut. This means that the pixels are binned appropriately, but the connection between pixels and image is broken.

The solution to this is to pass the symmetry operations all the way through to `cut_accumulate_data_` which should transform the pixels following the cut akin to how `symmetrise_sqw` transforms the pixels.

### PR DESCRIPTION
**Pull request by oerc0122**
Fixes #1620

### CODE REVIEW

File: horace_core/sqw/@sqw/private/cut_accumulate_data_.m [hunk 1]
```diff
@@ -225,6 +221,7 @@
         [npix, s, e, pix_ok, unique_runid_l, pix_indx, selected] = ...
             targ_proj(i).bin_pixels(targ_axes(i), candidate_pix, npix, s, e);
 
+        candidate_pix = sym.transform_pix(candidate_pix, {}, selected);
         candidate_pix = candidate_pix.tag(selected);
```
Comment (abuts) [inline horace_core/sqw/@sqw/private/cut_accumulate_data_.m:225]: As usual, do not understand the logic here. You loop over projections which project various areas of the sqw file to target area. But use only one sym operation for transforming pixels, while each projection should have its own. 
werid.

**Review by abuts — COMMENTED** [review]
When it fixed it seems ok. Do not like why one should provide two interconnected parameters (`sym{i}` and `proj{i}`) separately and not to bind them together, but as it works -- fine with this.

File: horace_core/sqw/@sqw/private/cut_accumulate_data_.m (hunk 1 above)
Comment (oerc0122) [reply horace_core/sqw/@sqw/private/cut_accumulate_data_.m:225]: Fixed that

**Review by cmarooney-stfc — APPROVED** [review]
