### PR TITLE
Fix section and add unit tests

### LINKED ISSUE #511: Uncertainty in section, recompute_urange
The code:
horace_core/sqw/@sqw/section.m , rows 105-107 contains algorithm, which recomputes img_range. 
namely:
```
      % Section the pix array, if sqw type, and update img_range
    if is_sqw_type(win(n))
        % Section pix array
        [nstart,nend] = aProjection.get_nrange(win(n).data.npix,irange);   % get contiguous ranges of pixels to be retained
        ind=ind_from_nrange(nstart,nend);
        wout(n).data.pix = win(n).data.pix.get_pixels(ind);
        %TODO: Do we actually need this? is this a suitable algorithm?
        wout(n).data.img_range=recompute_img_range(wout(n));
    end


```
Why does it is necessary, if img_range is correct?
Could we remove it? Could we replace it with transformation from pix_range to img_range using current projection?
the algorithm is also called recompute_urange --> should be removed to either recompute_img_range or whatever suitable

### LINKED ISSUE #800: section has no description and no unit tests
sqw object method "section" is a useful method, efficiently extracting part of an sqw object. Unfortunately it is not described in documentation and have no unit tests. It would disappear if not used in `align_crystal`

The ticket is to write unit test for the method.

### PR DESCRIPTION
**Pull request by oerc0122**
Fix section and add unit tests to verify

Fixes #800 
Fixes #511

### CODE REVIEW

File: horace_core/sqw/@sqw/section.m [hunk 1]
```diff
@@ -57,117 +56,97 @@
...
+    p=win(n).data.p;
+
     nbins_all_dims = win(n).data.axes.nbins_all_dims;
     img_range = win(n).data.axes.img_range;
-    p_ind = find(win(n).data.axes.nbins_all_dims>1); %what actual indexes of the projection axis along all DnD object indexes
-    % axis are among all indexes
-    for i=1:nargs
-        if isempty(varargin{i}) || (isscalar(varargin{i}) && isequal(varargin{i},0))
-            pax=win(n).data.dax(i);
+    tmp = img_range;
```
Comment (cmarooney-stfc) [inline horace_core/sqw/@sqw/section.m:72]: comment

File: horace_core/sqw/@sqw/section.m [hunk 2]
```diff
@@ -57,117 +56,97 @@
...
+    %what actual indices of the projection axis along all DnD object indices
+    % axis are among all indices
```
Comment (cmarooney-stfc) [inline horace_core/sqw/@sqw/section.m:74]: not sure I understand the comment

File: _test/test_sqw_class/test_section.m [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+
+        function obj = test_section_works(obj)
+            w = sqw.generate_cube_sqw(10);
+            test_sec = w.section([-3 3], [], [], []);
+            test_cut = w.cut(ortho_proj([1 0 0], [0 1 0]), [-2.5 1 2.5],[],[],[]);
+
+            assertEqualToTol(test_sec, test_cut);
+        end
+
+        function obj = test_section_collapse_dim(obj)
```
Comment (cmarooney-stfc) [inline _test/test_sqw_class/test_section.m:16]: think about test to show that section uses existing bins

**Review by cmarooney-stfc — CHANGES_REQUESTED** [review]

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 4]
```diff
@@ -2,166 +2,367 @@
...
+
+   The meaning of the first, second, third, etc. components changes between each form. Ensure that you have the correct
+   value in each component to ensure your cut is what you expect.
+
+* ``[]``
+  An empty binning range will use the current/previous binning axes in that dimension.
+
+* ``[n]``
+  if a single (scalar) number is given then that axis will be a plot axis and the bin width will be the
+  number you specify. The lower and upper limits are the (current|previous) binning axes in that dimension.
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:121]: current|previous - we discussed this. Guessing you mean the bins in the sqw before the cut. Not sure the best way of saying this but let's agree a way of saying this

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 5]
```diff
@@ -2,166 +2,367 @@
...
+.. warning::
+
+   A three-component binning axis defines the integration region by bin centres, i.e. the limits of the
+   data to be cut lie between ``min = lower-step/2`` and ``max = upper+step/2``, including ``min/max``
+   values. For example, ``[-1 1 1]`` will capture pixels from ``-1.5`` to ``1.5`` inclusive.
+
+
+* ``[lower, separation, upper, cut_width]``
+
+  A four-component binning axis defines multiple cuts with multiple integration limits in the selected direction.
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:155]: going to suggest that multiple is heavily emphasized, bold type and stars fore and aft.

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 6]
```diff
@@ -2,166 +2,367 @@
...
+  These components are:
+
+  * ``lower``
+
+    minimum cut centre
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:160]: not sure that centre by itself works here. Below, bin-centre is clear, but what is lower the centre of? Did you mean cut bin-centre?

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 7]
```diff
@@ -2,166 +2,367 @@
...
+   w1 = cut(w,[],[lo1,hi1],[lo2,hi2],...)
+
+.. note::
+
+   The number of binning arguments need only match the dimensionality of the object ``w`` (i.e. the number of plot
+   axes), so can be fewer than 4.
+
+.. note::
+
+   You cannot change the binning in a dnd object, i.e. you can only set the integration ranges and have to use ``[]``
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:217]:
```suggestion
   You cannot change the binning in a dnd object, i.e. you can only set the integration ranges, and have to use ``[]``
```

Presuming this is for cutting a dnd object. Here you don't have a set of pixels to rebin, and can only combine existing dnd bins. Do integration ranges still use the existing bins and does changing the range imply contracting the number of bins used?

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 8]
```diff
@@ -2,166 +2,367 @@
...
+   for the plot axis. The only option you have is to change the range of the plot axis by specifying ``[lo1,0,hi1]``
+   instead of ``[]`` (the '0' means 'use existing bin size') Note that Note also that
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:219]: seems to stop unexpectedly

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 9]
```diff
@@ -2,166 +2,367 @@
...
 
-   w1=cut(w,[],[lo1,hi1],[lo2,hi2],...)
 
+section
+=======
+
+``section`` is an ``sqw`` method, which works like a cut but uses the existing bins of an ``sqw`` object.
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:225]:
```suggestion
``section`` is an ``sqw`` method, which works like a cut but uses the existing bins of an ``sqw`` object rather than rebinning.
```

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 10]
```diff
@@ -2,166 +2,367 @@
...
-To take a cut from an existing sqw object and change the binning along one or more of the plot axes:
+  * ``[]``, ``[0]``
 
-::
+    Use entire original binning axis.
 
-   w1=cut(w, p1_bin, p2_bin,....)
+  * ``[lo, hi]``
 
+    Range containing bin centres to extract from ``w``
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:254]: are there restrictions on lo and hi, so that they must reduce the existing range, or will be ignored if they are outside the existing range

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 11]
```diff
@@ -2,166 +2,367 @@
...
+   info = head_sqw(filename);
 
-   info=head_sqw(filename,'-full')
+   info = head_sqw(filename,'-full')
 
 
-This is a function to give the header information in an SQW file or file to which an sqw object has been saved, whose full filename is given by the argument ``filename``. If the option ``'-full'`` is used then a fuller set of header information, rather than just the principal header, is returned.
+This is a function to give the header information in an SQW file or file to which an sqw object has been saved, whose
+full filename is given by the argument ``filename``. If the option ``'-full'`` is used then a fuller set of header
+information, rather than just the principal header, is returned.
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:311]: an example might be a good idea

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 12]
```diff
@@ -2,166 +2,367 @@
...
-::
+.. code-block:: matlab
 
-   output=read_dnd(filename);
+   output = read_dnd(filename);
 
 
-Exactly the same as above, but reads dnd data saved to file. If the file contains full sqw dataset, then it will be read as if it contained just a dnd dataset.
+Exactly the same as above, but reads dnd data saved to file. If the file contains full sqw dataset, then it will be read
+as if it contained just a dnd dataset.
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:359]: there was a time when a sqw (or dnd) could be constructed from the filename e.g. sqw(filename). Is this now deprecated?

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 13]
```diff
@@ -174,46 +375,62 @@ save_xye
...
+column of signal and another column of error (standard deviation).
 
 
 xye
 ===
 
 Extract the bin centres, intensity and standard errors from an sqw or dnd object.
 
-::
+.. code-block:: matlab
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:393]: does it make sense to put xye before save_xye?

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 14]
```diff
@@ -174,46 +375,62 @@ save_xye
...
 
-``qe1`` - Components of momentum (in rlu) and energy for each bin in the dataset. Generally, will be (n x 4) array, where n is the number of points
+* ``qe1``
+
+  Components of momentum (in rlu) and energy for each bin in the dataset. Generally, will be (n x 4) array, where n is the number of points
+
+* ``qe2``
 
-``qe2`` - For the second root
+  For the second root
```
Comment (cmarooney-stfc) [inline documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:436]: incomplete

**Review by cmarooney-stfc — CHANGES_REQUESTED** [review]

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 15]
```diff
@@ -2,166 +2,367 @@
...
+   my_cut = cut(data_source, proj, p1_bin, p2_bin, p3_bin, p4_bin)
+
+
+Where ``data_source`` is either a string giving the full filename (including path) of the input SQW file or just the
+variable containing SQW object stored in memory.
+
+Projection
+----------
+
+This defines the coordinate system you will use to plot the data.
```
[the remark this answers is not in the document]
Comment (oerc0122) [reply documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:24]: It defines the properties of the DnD, I've  tried to elaborate

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst [hunk 16]
```diff
@@ -2,166 +2,367 @@
...
-::
+   This is distinct from the vectors ``u`` and ``v`` that are specified in :ref:`gen_sqw
+   <manual/Generating_SQW_files:gen_sqw>`, which describe how the crystal is oriented with respect to the spectrometer
+   and are determined by the physical orientation of your sample.
 
-   my_cut = cut_sqw (data_source, proj, p1_bin, p2_bin, p3_bin)
+Lattice basis projections
+-------------------------
 
+The ``ortho_proj`` structure has several mandatory fields:
```
[the remark this answers is not in the document]
Comment (oerc0122) [reply documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:41]: That's mostly because that's all that I know about. @abuts will presumably document `spher_proj` and `cylindrical_proj` as and when

[the remark this answers is not in the document]
Comment (oerc0122) [reply documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:41]: Hence the empty blocks below

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst (hunk 11 above)
Comment (oerc0122) [reply documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:311]: I have no idea what this does. This is old stuff

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst (hunk 12 above)
Comment (oerc0122) [reply documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:359]: No, that's a more recent addition. This is old stuff

File: documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst (hunk 14 above)
Comment (oerc0122) [reply documentation/user_docs/docs/manual/Manipulating_and_extracting_data_from_SQW_files_and_objects.rst:436]: I'm not sure it is... What it means, I don't know. This is what was there originally
